"""Initial migration

Revision ID: 60cfdc84664c
Revises: 
Create Date: 2023-12-18 23:21:03.876944

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '60cfdc84664c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('data2')
    op.add_column('data1', sa.Column('Race_ethnicity', sa.Text(), nullable=True))
    op.drop_column('data1', 'Race/ethnicity')
    op.add_column('data3', sa.Column('Race_ethnicity', sa.Text(), nullable=True))
    op.alter_column('data3', 'SMM_Rate',
               existing_type=mysql.DOUBLE(asdecimal=True),
               type_=sa.Float(),
               existing_nullable=True)
    op.drop_column('data3', 'Race/ethnicity')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('data3', sa.Column('Race/ethnicity', mysql.TEXT(), nullable=True))
    op.alter_column('data3', 'SMM_Rate',
               existing_type=sa.Float(),
               type_=mysql.DOUBLE(asdecimal=True),
               existing_nullable=True)
    op.drop_column('data3', 'Race_ethnicity')
    op.add_column('data1', sa.Column('Race/ethnicity', mysql.TEXT(), nullable=True))
    op.drop_column('data1', 'Race_ethnicity')
    op.create_table('data2',
    sa.Column('my_row_id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('YEAR', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('SOURCE', mysql.TEXT(), nullable=True),
    sa.Column('QUESTION', mysql.TEXT(), nullable=True),
    sa.Column('PREVALENCE %', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('LOWER 95% CONFIDENCE INTERVAL', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.Column('UPPER 95% CONFIDENCE INTERVAL', mysql.DOUBLE(asdecimal=True), nullable=True),
    sa.PrimaryKeyConstraint('my_row_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
